#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D imgOutput;

void main()
{
    vec4 color = vec4(0, 0, 0, 1);
    ivec2 texCoordinates = ivec2(gl_GlobalInvocationID.xy);

    color.x = float(texCoordinates.x) / gl_NumWorkGroups.x;
    color.y = float(texCoordinates.y) / gl_NumWorkGroups.y;

    imageStore(imgOutput, texCoordinates, color);
} 